#!/usr/bin/env python3
"""Emit the box-certificate constants of the plain-ReLU trap as LaTeX macros.

The proof of the trap theorem prints a rational center, a box radius, an
upper-triangular Gram witness, an entrywise Hessian enclosure, a curvature
floor, and six gradient bounds.  All of them are literals of ``Plain.lean``.
This script reads them from the Lean source and writes
``generated/certificate_constants.tex`` so that the manuscript typesets the
numbers Lean checked, rather than a transcription.

``--check MAIN.TEX`` additionally reports whether the manuscript still
contains the numbers as hand-typed literals and whether those agree.

Usage:  python3 paper_tools/gen_certificate_constants.py [--check paper/main.tex]
"""

from __future__ import annotations

import argparse
import re
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEAN = ROOT / "Plain.lean"
OUT = Path(__file__).resolve().parent / "generated" / "certificate_constants.tex"

RATIONAL = re.compile(r"\(?(-?\d+)\s*/\s*(\d+)\)?")


def rationals(text: str) -> list[Fraction]:
    return [Fraction(int(a), int(b)) for a, b in RATIONAL.findall(text)]


def block(source: str, header: str) -> str:
    """The source text of one declaration, from its header to the next one."""
    start = source.index(header)
    end = re.search(r"^(?:theorem|def|lemma|private def|/--)", source[start + 1:], re.M)
    return source[start: start + 1 + (end.start() if end else len(source))]


def decimal(q: Fraction, digits: int) -> str:
    scaled = q * 10 ** digits
    if scaled.denominator != 1:
        raise SystemExit(f"{q} is not exact with {digits} decimals")
    n = scaled.numerator
    sign = "-" if n < 0 else ""
    n = abs(n)
    return f"{sign}{n // 10 ** digits}.{n % 10 ** digits:0{digits}d}"


def integer_over(q: Fraction, power: int) -> int:
    scaled = q * 10 ** power
    if scaled.denominator != 1:
        raise SystemExit(f"{q} is not an integer over 10^{power}")
    return scaled.numerator


def read_constants() -> dict:
    src = LEAN.read_text(encoding="utf-8")

    centre = block(src, "def seedCentre")
    masses, angles = centre.split("],", 1)
    masses_q = rationals(masses)
    angles_q = rationals(angles)
    if len(masses_q) != 3 or len(angles_q) != 3:
        raise SystemExit("seedCentre: expected three masses and three angles")

    enclosure = block(src, "theorem seed_hessian_gram_enclosure")
    head = enclosure.split(":= by", 1)[0]
    radii = sorted(set(rationals(head.split("∀ i j")[0])))
    if len(radii) != 1:
        raise SystemExit(f"seed_hessian_gram_enclosure: ambiguous box radius {radii}")
    radius = radii[0]
    shift, bound = rationals(head.split("∀ i j", 1)[1])[-2:]

    witness = block(src, "def seedGramWitness")
    rows = re.findall(r"!\[([^\[\]]*)\]", witness.split(":=", 1)[1])   # inner rows only
    matrix = [[Fraction(x.strip().strip("()").replace(" ", "")) for x in row.split(",")]
              for row in rows]
    if len(matrix) != 6 or any(len(r) != 6 for r in matrix):
        raise SystemExit("seedGramWitness: expected a 6×6 matrix")

    gradient = block(src, "theorem seed_center_gradient_sq")
    bounds = re.findall(r"\|gradient seedMass seedAngle (\d)\| ≤ \(\(([^)]*)\) : ℝ\)", gradient)
    bounds_q = [Fraction(0)] * 6
    for i, q in bounds:
        bounds_q[int(i)] = Fraction(q.replace(" ", ""))
    if any(b == 0 for b in bounds_q):
        raise SystemExit("seed_center_gradient_sq: missing a coordinate bound")

    floors = set(re.findall(r"\((1 / 16) : ℝ\) \* (?:pairEuclideanSq|\(\(∑)", src))
    if not floors:
        raise SystemExit("curvature floor 1/16 not found")
    floor = Fraction(1, 16)

    return {
        "masses": masses_q, "angles_over_pi": angles_q, "radius": radius,
        "shift": shift, "bound": bound, "matrix": matrix,
        "gradient": bounds_q, "floor": floor,
    }


def render(c: dict) -> str:
    masses = ",\\,".join(decimal(q, 12) for q in c["masses"])
    angles = ",\\,".join(decimal(q, 12) for q in c["angles_over_pi"])
    rows = " \\\\\n ".join(
        "&".join(str(integer_over(x, 6)) for x in row) for row in c["matrix"]
    )
    grad = ",".join(str(integer_over(q, 14)) for q in c["gradient"])
    sos = c["shift"] - c["floor"] - 6 * c["bound"]          # the completed-square remainder
    if sos <= 0:
        raise SystemExit("shift - floor - 6*bound is not positive")
    def frac(q: Fraction) -> str:
        return f"\\frac{{{q.numerator}}}{{{q.denominator}}}" if q.denominator != 1 else str(q.numerator)
    def inline(q: Fraction) -> str:
        return f"{q.numerator}/{q.denominator}"
    return "\n".join([
        "% Generated by paper_tools/gen_certificate_constants.py from Plain.lean; do not edit.",
        f"\\newcommand{{\\TrapMasses}}{{({masses})}}",
        f"\\newcommand{{\\TrapAnglesOverPi}}{{({angles})}}",
        f"\\newcommand{{\\TrapBoxRadius}}{{{inline(c['radius'])}}}",
        f"\\newcommand{{\\TrapGramScale}}{{10^{{-6}}}}",
        f"\\newcommand{{\\TrapGramMatrix}}{{\\begin{{pmatrix}}\n {rows}\n \\end{{pmatrix}}}}",
        f"\\newcommand{{\\TrapHessianShift}}{{{frac(c['shift'])}}}",
        f"\\newcommand{{\\TrapHessianBound}}{{{frac(c['bound'])}}}",
        f"\\newcommand{{\\TrapHessianBoundInline}}{{{inline(c['bound'])}}}",
        f"\\newcommand{{\\TrapHessianSixBound}}{{{frac(6 * c['bound'])}}}",
        f"\\newcommand{{\\TrapCurvatureFloor}}{{{frac(c['floor'])}}}",
        f"\\newcommand{{\\TrapCurvatureFloorInline}}{{{inline(c['floor'])}}}",
        f"\\newcommand{{\\TrapShiftMinusSixBound}}{{{frac(c['shift'] - 6 * c['bound'])}}}",
        f"\\newcommand{{\\TrapSosRemainder}}{{{frac(sos)}}}",
        f"\\newcommand{{\\TrapGradientScale}}{{10^{{-14}}}}",
        f"\\newcommand{{\\TrapGradientBounds}}{{({grad})}}",
        "",
    ])


def check(tex: Path, c: dict) -> int:
    text = tex.read_text(encoding="utf-8")
    expect = {
        "masses": ",\\,".join(decimal(q, 12) for q in c["masses"]),
        "angles": ",\\,".join(decimal(q, 12) for q in c["angles_over_pi"]),
        "radius": f"r={c['radius'].numerator}/{c['radius'].denominator}",
        "matrix row 1": "&".join(str(integer_over(x, 6)) for x in c["matrix"][0]),
        "gradient bounds": "(" + ",".join(str(integer_over(q, 14)) for q in c["gradient"]) + ")",
    }
    status = 0
    for name, literal in expect.items():
        if literal in text:
            print(f"  literal present and equal to Lean: {name}")
        elif "\\Trap" in text:
            print(f"  typeset through a macro: {name}")
        else:
            print(f"  MISMATCH or missing: {name} (expected {literal})")
            status = 1
    return status


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", type=Path, help="manuscript to compare against")
    args = parser.parse_args()
    c = read_constants()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(render(c), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return check(args.check, c) if args.check else 0


if __name__ == "__main__":
    sys.exit(main())
